[package]
name = "ipf"
version = "0.1.0"
edition = "2021"

[lib]
name = "ipf"
crate-type = ["dylib", "staticlib"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util"] }
