name: Build dmg On Push

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.70
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Build xcframework
        run: sh build-xcframework.sh

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3'

      - name: Xcode build
        run: |
          cd ui
          xcodebuild archive -scheme iPortForwarder -destination 'platform=macOS,name=Any Mac'

      - name: Make dmg
        run: |
          cd ~/Library/Developer/Xcode/Archives/*/*/Products/Applications
          hdiutil create ${{ github.workspace }}/iPortForwarder.dmg -volname iPortForwarder -fs HFS+ -srcfolder ./iPortForwarder.app -ov -format UDZO

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: iPortForwarder
          path: ${{ github.workspace }}/iPortForwarder.dmg
