name: Build Releases

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.83
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Build xcframework
        run: sh build-xcframework.sh

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'

      - name: Xcode build
        run: |
          cd ui
          xcodebuild archive \
            -scheme iPortForwarder \
            -destination 'platform=macOS,name=Any Mac' \
            -archivePath build.xcarchive

      - name: Make dmg
        run: |
          brew install graphicsmagick imagemagick
          npm install --global create-dmg
          # Ignore the failure since there is no code signing identity,
          # the DMG is still created and fine.
          create-dmg 'ui/build.xcarchive/Products/Applications/iPortForwarder.app' || true
          mv iPortForwarder*.dmg iPortForwarder.dmg

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/iPortForwarder.dmg
