name: Build Releases

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.71
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Build xcframework
        run: sh build-xcframework.sh

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3'

      - name: Xcode build
        run: |
          cd ui
          xcodebuild archive \
            -scheme iPortForwarder \
            -destination 'platform=macOS,name=Any Mac' \
            -archivePath build.xcarchive

      - name: Make dmg
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Install iPortForwarder" \
            --volicon "ui/build.xcarchive/Products/Applications/iPortForwarder.app/Contents/Resources/AppIcon.icns" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 128 \
            --icon "iPortForwarder.app" 150 150 \
            --hide-extension "iPortForwarder.app" \
            --app-drop-link 422 150 \
            --skip-jenkins \
            "iPortForwarder.dmg" \
            "ui/build.xcarchive/Products/Applications"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/iPortForwarder.dmg
